version: '3'
services:
  notebook:
    image: "stockmind/datascience-plus:latest"
    volumes:
      - ./work:/home/jovyan/
    ports:
      - "8888:8888"
    environment:
    - JUPYTER_ENABLE_LAB=yes